language: dart
sudo: false
dart:
  - stable
  - dev
script:
  - dartanalyzer --fatal-infos --fatal-warnings ./
  - dartfmt -n ./lib --set-exit-if-changed
  - pub get
  - pub global activate coverage
  - pub run test test/redux_logging_test.dart --coverage=coverage
  - pub global run coverage:format_coverage --in coverage/test/redux_logging_test.dart.vm.json --out lcov.info --lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
