name: redux_logging
description: Redux.dart Middleware that prints the latest action & state
version: 0.4.0
homepage: https://github.com/brianegan/redux_logging
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  redux: ">=4.0.0 <5.0.0"
  logging: ">=0.11.3 <0.12.0"

dev_dependencies:
  test: ">=1.0.0 <2.0.0"
